# Generated by Django 2.2.5 on 2019-09-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=300)),
                ('is_true', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=300)),
                ('Year', models.IntegerField()),
                ('Rated', models.CharField(max_length=300)),
                ('Released', models.CharField(max_length=300)),
                ('Runtime', models.CharField(max_length=300)),
                ('Genre', models.CharField(max_length=300)),
                ('Director', models.CharField(max_length=300)),
                ('Writer', models.CharField(max_length=300)),
                ('Actors', models.CharField(max_length=300)),
                ('Plot', models.CharField(max_length=300)),
                ('Language', models.CharField(max_length=300)),
                ('Country', models.CharField(max_length=300)),
                ('Awards', models.CharField(max_length=300)),
                ('Poster', models.CharField(max_length=300)),
                ('Metascore', models.CharField(max_length=300)),
                ('imdbRating', models.CharField(max_length=300)),
                ('imdbVotes', models.CharField(max_length=300)),
                ('imdbID', models.CharField(max_length=300)),
                ('Type', models.CharField(max_length=300)),
                ('DVD', models.CharField(max_length=300)),
                ('BoxOffice', models.CharField(max_length=300)),
                ('Production', models.CharField(max_length=300)),
                ('Website', models.CharField(max_length=300)),
                ('Response', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Raitings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=300)),
                ('Value', models.CharField(max_length=300)),
            ],
        ),
    ]
